name: ci-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  test:

    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: simplebank
          POSTGRES_PASSWORD: root
          POSTGRES_USER: root
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    
    - name: Setup Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.19
      id: go

    - name: Checkout code into Go module directory 
      uses: actions/checkout@v2
    
    - name: Migrate DB
      run: make migrateup

    - name: Test
      run: make test  


